In [19]:
import pandas as pd
df = pd.read_csv('yellow_tripdata_2021-01.csv.gz')

FileNotFoundError: [Errno 2] No such file or directory: 'green_tripdata_2021-01.csv.gz'

In [20]:
import pandas as pd
df = pd.read_csv('https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-01.csv.gz')

C:\Users\emman\AppData\Local\Temp\ipykernel_28984\2511618774.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2021-01.csv.gz')

In [21]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge
0,2.0,2021-01-01 00:15:56,2021-01-01 00:19:52,N,1.0,43,151,1.0,1.01,5.5,0.5,0.5,0.00,0.0,NaN,0.3,6.80,2.0,1.0,0.00
1,2.0,2021-01-01 00:25:59,2021-01-01 00:34:44,N,1.0,166,239,1.0,2.53,10.0,0.5,0.5,2.81,0.0,NaN,0.3,16.86,1.0,1.0,2.75
2,2.0,2021-01-01 00:45:57,2021-01-01 00:51:55,N,1.0,41,42,1.0,1.12,6.0,0.5,0.5,1.00,0.0,NaN,0.3,8.30,1.0,1.0,0.00
3,2.0,2020-12-31 23:57:51,2021-01-01 00:04:56,N,1.0,168,75,1.0,1.99,8.0,0.5,0.5,0.00,0.0,NaN,0.3,9.30,2.0,1.0,0.00
4,2.0,2021-01-01 00:16:36,2021-01-01 00:16:40,N,2.0,265,265,3.0,0.00,-52.0,0.0,-0.5,0.00,0.0,NaN,-0.3,-52.80,3.0,1.0,0.00

In [3]:
df[df['passenger_count'] ==0]

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
3,1.0,2021-01-01 00:15:48,2021-01-01 00:31:01,0.0,10.6,1.0,N,138,132,1.0,29.0,0.5,0.5,6.05,0.00,0.3,36.35,0.0
22,1.0,2021-01-01 00:16:27,2021-01-01 00:25:36,0.0,2.2,1.0,N,249,137,3.0,9.0,3.0,0.5,0.00,0.00,0.3,12.80,2.5
23,1.0,2021-01-01 00:37:59,2021-01-01 01:01:37,0.0,3.6,1.0,N,107,163,1.0,17.0,3.0,0.5,10.00,0.00,0.3,30.80,2.5
107,1.0,2021-01-01 00:27:44,2021-01-01 00:32:04,0.0,1.2,1.0,N,137,229,1.0,5.5,3.0,0.5,1.86,0.00,0.3,11.16,2.5
127,1.0,2021-01-01 00:45:19,2021-01-01 00:46:51,0.0,0.5,1.0,N,229,140,2.0,4.0,3.0,0.5,0.00,0.00,0.3,7.80,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1271081,1.0,2021-01-31 23:48:50,2021-02-01 00:29:22,0.0,11.1,1.0,N,138,236,1.0,37.0,3.0,0.5,100.00,6.12,0.3,146.92,2.5
1271221,1.0,2021-01-31 23:14:13,2021-01-31 23:24:20,0.0,2.2,1.0,N,48,239,1.0,9.5,3.0,0.5,1.50,0.00,0.3,14.80,2.5
1271223,1.0,2021-01-31 23:25:14,2021-01-31 23:48:06,0.0,6.8,1.0,N,148,151,1.0,22.5,3.0,0.5,6.55,0.00,0.3,32.85,2.5
1271224,1.0,2021-01-31 23:02:30,2021-01-31 23:08:24,0.0,1.7,1.0,N,48,90,1.0,7.0,3.0,0.5,2.15,0.00,0.3,12.95,2.5
1271225,1.0,2021-01-31 23:48:20,2021-02-01 00:12:23,0.0,8.2,1.0,N,68,244,2.0,25.5,3.0,0.5,0.00,0.00,0.3,29.30,2.5

In [3]:
dft = pd.read_csv("https://github.com/DataTalksClub/nyc-tlc-data/releases/download/yellow/yellow_tripdata_2019-01.csv.gz")

In [4]:
dft.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-01-01 00:46:40,2019-01-01 00:53:20,1,1.5,1,N,151,239,1,7.0,0.5,0.5,1.65,0.0,0.3,9.95,NaN
1,1,2019-01-01 00:59:47,2019-01-01 01:18:59,1,2.6,1,N,239,246,1,14.0,0.5,0.5,1.00,0.0,0.3,16.30,NaN
2,2,2018-12-21 13:48:30,2018-12-21 13:52:40,3,0.0,1,N,236,236,1,4.5,0.5,0.5,0.00,0.0,0.3,5.80,NaN
3,2,2018-11-28 15:52:25,2018-11-28 15:55:45,5,0.0,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,7.55,NaN
4,2,2018-11-28 15:56:57,2018-11-28 15:58:33,5,0.0,2,N,193,193,2,52.0,0.0,0.5,0.00,0.0,0.3,55.55,NaN

In [5]:
dft.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7667792 entries, 0 to 7667791
Data columns (total 18 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   object
 2   tpep_dropoff_datetime  object
 3   passenger_count        int64
 4   trip_distance          float64
 5   RatecodeID             int64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
dtypes: float64(9), int64(6), object(3)
memory usage: 1.0+ GB

In [18]:
from pathlib import PurePosixPath

color = "yellow"
year = 2021
month = 1
datafile = f"{color}_tripdata_{year}-{month:02}"
path = PurePosixPath(f"data/{color}/{datafile}.parquet")
print(path)

data/yellow/yellow_tripdata_2021-01.parquet

In [18]:
import numpy as np
from scipy.optimize import bisect
import matplotlib.pyplot as plt
import ipywidgets as widgets

def solve_diff_eq(C0, C_inf, v, dp, Dl, t_max, dt, dx, L):
    k = v * dp / Dl
    Nt = int(t_max / dt)
    Nx = int(L / dx) + 1
    C = np.zeros((Nt + 1, Nx + 1))
    C[0, :] = C0
    for n in range(Nt):
        for i in range(1, Nx):
            C[n + 1, i] = C[n, i] + k * dt / dx**2 * (C[n, i + 1] - 2 * C[n, i] + C[n, i - 1])
    C[:, -1] = C_inf
    x = np.linspace(0, L, Nx + 1)
    return C, x



def solve_reactor_length(v, dp, Dl, C_inf, L, t_max, dt, dx):
    C, x = solve_diff_eq(C0, C_inf, v, dp, Dl, t_max, dt, dx, L)
    C_eff = C_inf * 0.99

    def residual(L):
        C, x = solve_diff_eq(C0, C_inf, v, dp, Dl, t_max, dt, dx, L)
        return C[-1, -1] - C_eff

    L_opt = bisect(residual, 0, L)
    return L_opt




# plot of solution


def update_plot(v, dp, Dl):
    L_opt = solve_reactor_length(v, dp, Dl, C_inf, L, t_max, dt, dx)
    C, x = solve_diff_eq(C0, C_inf, v, dp, Dl, t_max, dt, dx, L_opt)

    C_eff = 0.99 * C_inf  # 99% saturation
    idx = np.argwhere(C[-1, :] >= C_eff)[0][0]
    x_99 = x[idx]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))
    ax1.plot(x, C[-1, :])
    ax1.axhline(y=C_eff, color='r', linestyle='--')
    ax1.axvline(x=x_99, color='r', linestyle='--')
    ax1.set_xlabel('Position [m]')
    ax1.set_ylabel('Concentration [mol/m^3]')
    ax1.set_title('Percent Saturation')



# Plotting the contact time
    x = np.linspace(0, L[-1], 1000)
    tau = x/v
    ax2.plot(x, tau)
    ax2.set_xlabel('Reactor Length (x)')
    ax2.set_ylabel('Contact Time (tau)')
    ax2.set_title('Contact Time vs. Reactor Length')

    plt.show()

def reset_sliders(b):
    v.value = 0.1
    dp.value = 1
    Dl.value = 1e-9

v = widgets.FloatText(description='v', value=0.1)
dp = widgets.FloatText(description='dp', value=1)
Dl = widgets.FloatText(description='Dl', value=1e-9)

v_slider = widgets.FloatSlider(min=0.1, max=1, step=0.1, value=0.1, description='')
dp_slider = widgets.FloatSlider(min=0.1, max=10, step=0.1, value=1, description='')
Dl_slider = widgets.FloatSlider(min=1e-9, max=1e-7, step=1e-9, value=1e-9, description='')
reset_button = widgets.Button(description='Reset Sliders')
reset_button.on_click(reset_sliders)

C0 = 0  # Initial concentration
C_inf = 1  # Solute concentration in the feed
L = 1  # Reactor length
t_max = 10  # Maximum simulation time
dt = 0.1  # Time step
dx = 0.01  # Space step

widgets.interactive(update_plot, v=[0.1, 1, 0.1], dp=[0.1, 1, 0.1],
                    Dl=[0.1, 1, 0.1])
display(reset_button)



def main():
    C0=0
    C_inf=0.89
    v=0.1
    dp=1
    Dl=1
    t_max=1
    dt=0.1
    dx=0.01
    L=1

    update_plot(v, dp, Dl)

if __name__=="__main__":
    main()

Button(description='Reset Sliders', style=ButtonStyle())

ValueError: negative dimensions are not allowed

In [29]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp
import ipywidgets as widgets

# Constants
kf = 0.1
Ceff = 0.99
L = 1

# Calculating mass transfer coefficient
def mass_transfer_coefficient(v, dp, Dl):
    return kf*(v/Dl)/(1 + (v/Dl)*(dp/kf))

# Solving the differential equation
def solve_diff_eq(v, dp, Dl):
    k = mass_transfer_coefficient(v, dp, Dl)
    C0 = [0]
    x = np.linspace(0, L, 1000)
    sol = solve_ivp(lambda x, C: k*(Ceff - C), [0, L], C0, t_eval=x)
    return sol.t, sol.y[0]

def update_plot(v, dp, Dl):
    x, C = solve_diff_eq(v, dp, Dl)
    plt.figure(figsize=(12, 8))
    plt.subplot(121)
    plt.plot(x, C)
    plt.ylabel("Depth (L)")
    plt.xlabel("Concentration (C)")
    plt.title("% Saturation vs Depth")
    
    plt.subplot(122)
    v = np.linspace(0, v, 1000)
    t = [L/v for v in v]
    plt.plot(x, t)
    plt.xlabel("Depth (L)")
    plt.ylabel("Residence Time (t)")
    plt.title("Residence Time vs Depth")
    
    plt.tight_layout()
    plt.show()

v = widgets.FloatSlider(value=0.1, min=0.1, max=1.0, description='v')
dp = widgets.FloatSlider(value=0.1, min=0.1, max=1.0, description='dp')
Dl = widgets.FloatSlider(value=0.1, min=0.1, max=1.0, description='Dl')
widgets.interactive(update_plot, v=v, dp=dp, Dl=Dl)

interactive(children=(FloatSlider(value=0.1, description='v', max=1.0, min=0.1), FloatSlider(value=0.1, descri…

In [1]:
import pandas as pd
df = pd.read_csv("https://github.com/DataTalksClub/nyc-tlc-data/releases/download/fhv/fhv_tripdata_2019-01.csv.gz")

In [3]:
df.head(20)

,dispatching_base_num,pickup_datetime,dropOff_datetime,PUlocationID,DOlocationID,SR_Flag,Affiliated_base_number
0,B00001,2019-01-01 00:30:00,2019-01-01 02:51:55,NaN,NaN,NaN,B00001
1,B00001,2019-01-01 00:45:00,2019-01-01 00:54:49,NaN,NaN,NaN,B00001
2,B00001,2019-01-01 00:15:00,2019-01-01 00:54:52,NaN,NaN,NaN,B00001
3,B00008,2019-01-01 00:19:00,2019-01-01 00:39:00,NaN,NaN,NaN,B00008
4,B00008,2019-01-01 00:27:00,2019-01-01 00:37:00,NaN,NaN,NaN,B00008
5,B00008,2019-01-01 00:48:00,2019-01-01 01:02:00,NaN,NaN,NaN,B00008
6,B00008,2019-01-01 00:50:00,2019-01-01 00:59:00,NaN,NaN,NaN,B00008
7,B00008,2019-01-01 00:51:00,2019-01-01 00:56:00,NaN,NaN,NaN,B00008
8,B00009,2019-01-01 00:44:00,2019-01-01 00:58:00,NaN,NaN,NaN,B00009
9,B00009,2019-01-01 00:19:00,2019-01-01 00:36:00,NaN,NaN,NaN,B00009
10,B00009,2019-01-01 00:36:00,2019-01-01 00:49:00,NaN,NaN,NaN,B00009
11,B00009,2019-01-01 00:26:00,2019-01-01 00:32:00,NaN,NaN,NaN,B00009
12,B00009,2019-01-01 00:26:00,2019-01-01 00:36:00,NaN,NaN,NaN,B00009
13,B00009,2019-01-01 00:58:00,2019-01-01 01:05:00,NaN,NaN,NaN,B00009
14,B00013,2019-01-01 00:02:29,2019-01-02 00:25:30,NaN,NaN,NaN,B00013
15,B00013,2019-01-01 00:01:33,2019-01-02 00:18:16,NaN,NaN,NaN,B00013
16,B00037,2019-01-01 00:02:43,2019-01-01 00:10:14,NaN,265.0,NaN,B00037
17,B00037,2019-01-01 00:26:02,2019-01-01 00:37:00,NaN,265.0,NaN,B00037
18,B00037,2019-01-01 00:11:16,2019-01-01 00:25:41,NaN,265.0,NaN,B00037
19,B00037,2019-01-01 00:33:45,2019-01-01 00:45:28,NaN,265.0,NaN,B00037

In [7]:
# Pre_transformation: columns data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23143222 entries, 0 to 23143221
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   dispatching_base_num    object
 1   pickup_datetime         object
 2   dropOff_datetime        object
 3   PUlocationID            float64
 4   DOlocationID            float64
 5   SR_Flag                 float64
 6   Affiliated_base_number  object
dtypes: float64(3), object(4)
memory usage: 1.2+ GB

In [8]:
df['dispatching_base_num'] = df['dispatching_base_num'].astype(str)
df['pickup_datetime'] =pd.to_datetime(df['pickup_datetime'])
df['dropOff_datetime'] =pd.to_datetime(df['dropOff_datetime'])
df['PUlocationID'] = df['PUlocationID'].astype(float)
df['DOlocationID'] = df['DOlocationID'].astype(float)
df['SR_Flag'] = df['SR_Flag'].astype(float)
df['Affiliated_base_number'] = df['Affiliated_base_number'].astype(str)

In [9]:
# Post_transformation: columns data type
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23143222 entries, 0 to 23143221
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   dispatching_base_num    object
 1   pickup_datetime         datetime64[ns]
 2   dropOff_datetime        datetime64[ns]
 3   PUlocationID            float64
 4   DOlocationID            float64
 5   SR_Flag                 float64
 6   Affiliated_base_number  object
dtypes: datetime64[ns](2), float64(3), object(2)
memory usage: 1.2+ GB

In [8]:
import math
count = 0

for i in range(2,5):
    root_of_value = math.sqrt(i)
    print(int(root_of_value), int(root_of_value)**2, i)
    if root_of_value**2 == i:
        
        count += 1
        
print(count)

1 1 2
1 1 3
2 4 4
1

In [9]:
math.sqrt(10**9)

31622.776601683792

In [24]:
math.fl(math.sqrt(35))

5

In [ ]:
6 7